### PR TITLE
Add dtc compatible with 3.8.13 kernel

### PR DESCRIPTION
**Pull request by cdsteinkuehler**
Use RCN's script to fetch and build a dtc compiler compatible with
the 3.8.13 kernel used by the Machinekit image.

General cleanup of the machinekit/scripts directory

Signed-off-by: Charles Steinkuehler <charles@steinkuehler.net>

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Thanks!

**Comment by RobertCNelson** [comment]
ps, re-queue-ing the weekly builder, so this will be part of this week's image. ;)

**Comment by cdsteinkuehler** [comment]
On 11/20/2016 10:05 AM, Robert Nelson wrote:
> ps, re-queue-ing the weekly builder, so this will be part of this week's image. ;)

Thanks!!

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by RobertCNelson** [comment]
My jenkins build bot didn't like something:

http://rcn-ee.homeip.net:8080/job/weekly_bb.org_machinekit-debian-jessie/18/console

so i reworked it:

https://github.com/RobertCNelson/omap-image-builder/commit/4ab9d5fea5440927e9a9495d3b90396d675e4cc3

https://github.com/RobertCNelson/boot-scripts/commit/66e42b05a39b7d7aab745da2de8ddaa68b7ba09d

**Comment by cdsteinkuehler** [comment]
On 11/20/2016 11:55 AM, Robert Nelson wrote:
> My jenkins build bot didn't like something:
> 
> http://rcn-ee.homeip.net:8080/job/weekly_bb.org_machinekit-debian-jessie/18/console
> 
> so i reworked it:
> 
> 4ab9d5f 
> <https://github.com/RobertCNelson/omap-image-builder/commit/4ab9d5fea5440927e9a9495d3b90396d675e4cc3>
> 
> RobertCNelson/boot-scripts@66e42b0 
> <https://github.com/RobertCNelson/boot-scripts/commit/66e42b05a39b7d7aab745da2de8ddaa68b7ba09d>

Yeah, I had a nasty time getting your dtc.sh script running, but I
though the version I pushed was working.

Regardless, the new way looks much better, thanks!

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by RobertCNelson** [comment]
ah, i think i found it..

"sudo rsync"..

added:
```
/usr/bin/rsync
```
to my /etc/sudoers on the build bots..

**Comment by cdsteinkuehler** [comment]
On 11/20/2016 2:23 PM, Robert Nelson wrote:
> ah, i think i found it..
> 
> "sudo rsync"..

I believe the rsync failed because you deleted all the files it would
have copied.

...but that's OK, because the files were only scripts to build the dtc
utility which you're now building in a different (and better!) way.

So there are some warning messages and (unimportant) errors in the
output, but it looks like everything builds OK.  I'm going to try and
take some time next week to do some testing, clean things up, and add
some SoC+FPGA target image configurations, so look for another PR
soon-ish.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Pull request merged**
